dataset_ratio: 0.4
batch_size: 32
scale: 1000.

model:
  name: DenseNetV2
  out_chans: 1
  encoder: densenet
  backbone: densenet161

dataset:
  output_type: depth

optimizer:
  name: AdamW

scheduler:
  name: none
  