dataset_ratio: 1.0

model:
  name: DenseNetV2
  out_chans: 15
  encoder: "densenet"
  backbone: "densenet161"
  imagenet_pretrained: True

dataset:
  output_type: "all"
  dataset_path: "../DenseTact-Calibration-M/sim_dataset"

optimizer:
  name: AdamW