dataset_ratio: 0.4

model:
  name: DenseNetV2
  out_chans: 3
  encoder: "densenet"
  backbone: "densenet161"
  imagenet_pretrained: True

dataset:
  output_type: "full"
  dataset_path: "real_world_dataset"

optimizer:
  name: AdamW

scheduler:
  name: "none"