dataset_ratio: 0.8

model:
  name: DenseNetV2
  out_chans: 1
  encoder: "densenet"
  backbone: "densenet161"
  imagenet_pretrained: True

dataset:
  output_type: "depth"
  dataset_path: "real_world_depth"

optimizer:
  name: Adam

scheduler:
  name: none