dataset_ratio: 0.4
gradient_clip_val: 0.1
gradient_clip_algorithm: value

model:
  name: HieraDPT
  out_chans: 1
  pretrained_model: "exp/Hiera2_MAE/checkpoints/last.ckpt"

  hiera:
    use_bn: True
    decoder_embed_dim: 512

dataset:
  output_type: "depth"

optimizer:
  name: AdamW
  lr: 0.0005

scheduler:
  name: linear_cosine
  warmup: 2000
  cycle_k: 1