dataset_ratio: 0.75
batch_size: 12
epochs: 150

# loss:
#   stress_weight: 10.
scales:
  disp: 1.
  stress: 1.
  stress2: 1.
  cnorm: 1.

loss:
  stress_weight: 1.
  stress2_weight: 1.
  cnorm_weight: 1.
  disp_weight: 1. 

model:
  name: HieraDPT
  out_chans: [3, 3]
  # pretrained_model: "exp/HieraRealMAE/checkpoints/last.ckpt"
  pretrained_model: "exp/DT_Model/checkpoints/last.ckpt"
  LoRA: False

  hiera:
    decoder: "QUpsampling"
    decoder_embed_dim: 512
    decoder_num_heads: 16
    decoder_depth: 8

dataset:
  # output_type: ['normal', 'shear', 'disp', 'cnorm']
  output_type: ['shear', 'disp']
  contiguous_on_direction: False

optimizer:
  name: AdamW
  lr: 0.001

metric:
  PN_thresh: 0.001
  TF_abs_error_thresh: 0.01

scheduler:
  name: linear_cosine
  warmup: 2000