dataset_ratio: 1.0
batch_size: 16
scale: 1.
epochs: 100

scales:
  disp: 1.
  stress: 1.
  cnorm: 1.

loss:
  stress_weight: 1.
  stress2_weight: 1.
  cnorm_weight: 1.
  disp_weight: 1. 

model:
  name: HieraDPT
  out_chans: [3, 3, 3, 3]
  LoRA: False

  hiera:
    decoder: "QUpsampling"
    decoder_embed_dim: 512
    decoder_num_heads: 16
    decoder_depth: 8

dataset:
  output_type: ['normal', 'disp', 'cnorm'] # , 'cnorm', 'cshear'
  contiguous_on_direction: False
  normalization: False

optimizer:
  name: AdamW
  lr: 0.001

metric:
  PN_thresh: 0.001
  TF_abs_error_thresh: 0.01

scheduler:
  name: linear_cosine
  warmup: 2000