dataset_ratio: 1.0
batch_size: 16
scale: 1.0
epochs: 2

scales:
  stress: 10000.

model:
  name: HieraDPT
  out_chans: [3, 3, 3, 3]

  hiera:
    decoder: "QUpsampling"
    decoder_embed_dim: 512
    decoder_num_heads: 16
    decoder_depth: 8

dataset:
  output_type: ["shear", "disp", "cnorm", "normal"]

optimizer:
  name: AdamW
  lr: 0.001

metric:
  PN_thresh: 0.001
  TF_abs_error_thresh: 0.01

scheduler:
  name: linear_cosine
  warmup: 2000