dataset_ratio: 1.0
batch_size: 24
epochs: 150

loss:
  stress_weight: 10.

model:
  name: HieraDPT
  out_chans: [3, 3]
  pretrained_model: "exp/HieraRealMAE/checkpoints/last.ckpt"
  LoRA: True

  hiera:
    decoder: "QUpsampling"
    decoder_embed_dim: 512
    decoder_num_heads: 16
    decoder_depth: 8

dataset:
  output_type: ["disp", "stress1"]
  contiguous_on_direction: False

optimizer:
  name: AdamW
  lr: 0.001

metric:
  PN_thresh: 0.001
  TF_abs_error_thresh: 0.01

scheduler:
  name: linear_cosine
  warmup: 2000