dataset_ratio: 1.0

model:
  name: DenseNetV2
  out_chans: 1
  encoder: "resnext"
  backbone: "resnext101_32x8d"
  imagenet_pretrained: True

dataset:
  output_type: "depth"
  dataset_path: "../DenseTact-Calibration-M/sim_dataset"

optimizer:
  name: AdamW