dataset_ratio: 0.75

model:
  name: DenseNetV2
  out_chans: 1
  encoder: "resnet"
  backbone: "resnet152"
  imagenet_pretrained: False

dataset:
  output_type: "depth"
  dataset_path: "../DenseTact-Calibration-M/sim_dataset"

optimizer:
  name: AdamW

scheduler:
  name: "none"
  