dataset_ratio: 1.0

model:
  name: DenseNetV2
  out_chans: 3
  encoder: "resnet"
  backbone: "resnet101"
  imagenet_pretrained: True

dataset:
  output_type: "full"
  dataset_path: "real_world_dataset"

optimizer:
  name: Adam

scheduler:
  name: "none"