dataset_ratio: 0.4
epochs: 100

# training parameters
learning_rate: 0.001
finetune_ratio: 0.8

model:
  name: ViT
  out_chans: 1
  pretrained_model: "exp/MAE_ViT_Pretrain_75/checkpoints/last.ckpt"

dataset:
  output_type: "depth"